Dev
WildCodeSchool/2023-02-JS-FT-Lyon-P3-Serenity pull request #29
Opened 2023-06-26 07:20 UTC by LightQv

2023-06-26 10:42 UTC, PPaillard requested changes
Je vous laisse regarder les changemznts à faire en commentaire.

2023-06-26 10:42 UTC, PPaillard commented on .gitignore
> +.env
Ya pas de .env à la racine du projet..

2023-06-26 10:42 UTC, PPaillard commented on .DS_Store
ajouter .DS_Store au gitignore

2023-06-26 10:42 UTC, PPaillard commented on backend/database.sql
> +
Pas de code commenté

2023-06-26 10:42 UTC, PPaillard commented on backend/migrate.js
> +  // generateRandomInterventions(20);
Pas de code commenté

2023-06-26 10:42 UTC, PPaillard commented on frontend/.env.sample
> +VITE_BACKEND_URL=YOUR_BACKEND_URL
Laissez un exemple comme ça quand qqu'un utilise votre projet, il sait s'il y a un slash à la fin ou pas par exemple, etc.

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/assets/images/welcome.jpg
Réduire la taille de l'image

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/assets/logo-txt.png
Utilisez le svg s'il est dispo plutôt que le png.

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/assets/logo-txt-white.png
Utilisez le svg s'il est dispo plutôt que le png.

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/components/admin/dashboard/InsightCard.jsx
> +    return null;
Ca me parait super étrange ça. Il faut m'expliquer cette fonction parce que tester la présence du mail pour envoyer le firstname... c'est étrange

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/components/admin/patients/ListPatients.jsx
> +export default function ListPatients({
Le composant est mal nommé, c'est un seul patient qui est affiché

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/components/admin/practitioners/PractitionersList.jsx
> +export default function PractitionersList({
Mauvais nom, ça n'affiche qu'un praticien.
De plus, si vous écrivez une fois 
listMachin
et la fois d'après
trucsList
C'est pas une bonne chose, restez cohérent dans vos nommages.

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/components/admin/protocols/ProtocolsList.jsx
> +export default function ProtocolsList({
idem

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/components/routes/Layout.jsx
Pas compris l'utilité de ce composant

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/main.jsx
> +    <React.StrictMode>
Le strictmode doit tout entourer

2023-06-26 10:42 UTC, PPaillard commented on frontend/src/pages/admin/AdminPractitioners.jsx
> +  });
Enfin des noms "propres" :p

2023-06-26 10:42 UTC, PPaillard commented on package.json
> +    "yup": "^1.2.0"
Aucune dépendance dans le package.json global.

2023-06-27 08:02 UTC, MargauxDF approved these changes

2023-06-27 09:16 UTC, merged